### ISSUE TITLE
Fix Windows not being able to delete temporary files

### ISSUE THREAD

**Issue by makuto** [junkblocker/codesearch#13]
Hi,
The Windows version of codesearch is broken because it doesn't properly close any of its file handles before it tries to remove the files.

My fork has [this change](https://macoy.me/code/macoy/codesearch/commit/c5f1d5ebd4e48099be0970402d5218c9fd7ac1e8) which fixes this. My fork has diverged (I added a `tempDir` argument so that I could move the temp files where I wanted them), but someone should be able to port over my changes without too much issue.

**Comment by junkblocker** [comment]
Thanks, @makuto! I'll take a look and port.

**Comment by junkblocker** [comment]
@makuto - Ported. I don't have a windows machine to test this on so if you could please let me know if this works for you,  I'll close it.

**Comment by junkblocker** [comment]
Closing for releasing binaries. Please reopen if somebody sees an issue.
